[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "robot_pkg"
description = "An Example Project"
version = "0.1.0"
dependencies = [
    'pyyaml',
    'py_trees',
    'python-can',
    'pigpio',
    'smbus'
]



[project.scripts]
start_main = "robot_pkg.main:main_func"
echo_log = "robot_pkg.utils:echo_log"