idf_component_register(SRCS "main.c" "gptimer/gptimer.c" "mcpwm/mcpwm.c" "motor_control/motor_control.c" "pcnt/pcnt.c" "microswitch/microswitch.c" "control/control.c" "wifi/wifi/wifi.c" "wifi/socket/socket.c" "wifi/credentials/credentials.c"
                            "gpio/gpio.c" "i2c/i2c.c" "tof/tof_api.c"
                            "tof/tof_i2c.c" "tof/tof.c" "utils/vector.c" "tof/point_cloud.c" "utils/utils.c"
                    INCLUDE_DIRS ".")