[loggers]
keys=root, main, execute, actuators, servo, sensors

[handlers]
keys=stdout, file

[formatters]
keys=default

[logger_root]
level=NOTSET
handlers=stdout

[logger_main]
level=DEBUG
handlers=stdout, file
propagate=0
qualname=main

[logger_execute]
level=DEBUG
handlers=stdout, file
propagate=0
qualname=execute

[logger_actuators]
level=DEBUG
handlers=stdout, file
propagate=0
qualname=actuators

[logger_servo]
level=DEBUG
handlers=stdout, file
propagate=0
qualname=servo

[logger_sensors]
level=DEBUG
handlers=stdout, file
propagate=0
qualname=sensors


[handler_stdout]
class=StreamHandler
level=DEBUG
formatter=default
args=(sys.stdout,)

[handler_file]
class=FileHandler
level=DEBUG
formatter=default
args=('%(log_filename)s.log', 'w')

[formatter_default]
class=logging.Formatter
format=[%(levelname)-7s][%(asctime)s]:%(name)s: %(message)s
datefmt=%H:%M:%S
style=%
