[loggers]
keys=root, main, can, nfs, odom, execute, outputs, inputs, servo, move, lidar, sima

[handlers]
keys=stdout, file

[formatters]
keys=default

[logger_root]
level=NOTSET
handlers=stdout

[logger_main]
level=DEBUG
handlers=stdout, file
propagate=0
qualname=main

[logger_can]
level=INFO
handlers=stdout, file
propagate=0
qualname=can

[logger_nfs]
level=DEBUG
handlers=file
propagate=0
qualname=nfs

[logger_odom]
level=DEBUG
handlers=file
propagate=0
qualname=odom

[logger_execute]
level=DEBUG
handlers=stdout, file
propagate=0
qualname=execute

[logger_outputs]
level=DEBUG
handlers=stdout, file
propagate=0
qualname=outputs

[logger_servo]
level=DEBUG
handlers=stdout, file
propagate=0
qualname=servo

[logger_move]
level=DEBUG
handlers=stdout, file
propagate=0
qualname=move

[logger_lidar]
level=DEBUG
handlers=stdout, file
propagate=0
qualname=lidar

[logger_inputs]
level=DEBUG
handlers=stdout, file
propagate=0
qualname=inputs

[logger_sima]
level=DEBUG
handlers=stdout, file
propagate=0
qualname=sima


[handler_stdout]
class=StreamHandler
level=DEBUG
formatter=default
args=(sys.stdout,)

[handler_file]
class=FileHandler
level=DEBUG
formatter=default
args=('%(log_filename)s.log', 'w')

[handler_filecan]
class=FileHandler
level=DEBUG
formatter=default
args=('can.log', 'w')

[formatter_default]
class=logging.Formatter
format=[%(levelname)-7s][%(asctime)s]:%(name)s: %(message)s
datefmt=%H:%M:%S
style=%
